---
permalink: api/reference_element_api_binding_vvols.html 
sidebar: sidebar 
keywords: binding,object,objects,volume,volumes,virtual 
summary: O objeto de encadernação contém informações sobre a vinculação de um volume virtual. Você pode recuperar uma lista dessas informações para todos os volumes virtuais usando o método ListVirtualVolumeBindings API. 
---
= encadernação (volumes virtuais)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O objeto de encadernação contém informações sobre a vinculação de um volume virtual. Você pode recuperar uma lista dessas informações para todos os volumes virtuais usando o `ListVirtualVolumeBindings` método API.



== Membros do objeto

Este objeto contém os seguintes membros:

|===
| Nome | Descrição | Tipo 


 a| 
ProtocolEndpointID
 a| 
A ID exclusiva do endpoint do protocolo.
 a| 
UUID



 a| 
ProtocolEndpointInBandID
 a| 
O scsiNAADeviceID do endpoint do protocolo.
 a| 
cadeia de carateres



 a| 
ProtocolEndpointType
 a| 
O tipo de endpoint de protocolo. SCSI é o único valor retornado para o tipo de endpoint de protocolo.
 a| 
cadeia de carateres



 a| 
VirtualVolumeBindingID
 a| 
O ID exclusivo do objeto de vinculação de volume virtual.
 a| 
número inteiro



 a| 
VirtualVolumeHostID
 a| 
O ID exclusivo do host de volume virtual.
 a| 
UUID



 a| 
VirtualVolumeID
 a| 
O ID exclusivo do volume virtual.
 a| 
UUID



 a| 
VirtualVolumeSecondaryID
 a| 
A ID secundária do volume virtual.
 a| 
cadeia de carateres

|===


== Encontre mais informações

* xref:reference_element_api_listvirtualvolumebindings.adoc[ListVirtualVolumeBindings]
* xref:reference_element_api_protocolendpoint.adoc[ProtocolEndpoint]

